### ISSUE TITLE
[BUG: SEGV] get_trusted_dev_file does not check if string is NULL before executing strlen

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#73]
## Purpose
* Patch yet another security vulnerability
* Program crashes if the string parameters (i.e. `char *) is `NULL

## Tasks/Goals
- [ ] Check if string is NULL at the beginning of the function

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*

**Comment by zakuArbor** [comment]
### Run Ouput
* was reading a book on GDB and it was talking about SEGV when strings were NULL which made me think about my project. So I tested it hours later and indeed it broke.
```
17:41 [zaku:~/Documents/projects/proxyAuth/pam]
$ ./pam_test 
AddressSanitizer:DEADLYSIGNAL
=================================================================
==154048==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000401fd0 bp 0x7ffcca1a3b20 sp 0x7ffcca1a29c0 T0)
==154048==The signal is caused by a READ memory access.
==154048==Hint: address points to the zero page.
    #0 0x401fd0 in get_trusted_dev_file src/pam_bt_trust.c:44
    #1 0x401429 in main src/pam_test.c:47
    #2 0x7f43e253855f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)
    #3 0x7f43e253860b in __libc_start_main_alias_1 (/lib64/libc.so.6+0x2d60b)
    #4 0x4012f4 in _start (/home/zaku/Documents/projects/proxyAuth/pam/pam_test+0x4012f4)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/pam_bt_trust.c:44 in get_trusted_dev_file
==154048==ABORTING
```
