### ISSUE TITLE
[Leak] On a989aac, pam_test detects a leak

### ISSUE THREAD

**Issue by zakuArbor** [zakuArbor/proxyAuth#74]
## Purpose
* Leak detected while trying to patch #73 
* Leak was introduced before commit a989aac
```
$ git log | head
commit a989aac6a58d82fced16ea93b1c7dfffbb365946
Merge: dc3d1e9 526050b
Author: Ju Hong Kim <nabimoon1234@gmail.com>
Date:   Thu Feb 10 01:17:20 2022 -0500

    Merge pull request #70 from zakuArbor/69-action-bug
    
    [#69] Fix regex to match OS Attempt - Abusing admin privileges

commit 526050bfc190a7245c3ec19a72999791c45dc445
18:03 [zaku:~/Documents/projects/proxyAuth/pam]
$ ./pam_test 
start bluetooth_login
pika: 20:DA:22:DE:0F:68
checking file: /etc/proxy_auth/
checking file: /etc/proxy_auth/zaku
Welcome zaku. Login via Auth Proxy.

=================================================================
==155621==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 18 byte(s) in 1 object(s) allocated from:
    #0 0x7f0d42eab91f in __interceptor_malloc (/lib64/libasan.so.6+0xae91f)
    #1 0x401e72 in find_trusted_paired_device src/pam_bt_trust.c:14
    #2 0x4023a4 in bluetooth_login src/pam_bt_trust.c:151
    #3 0x401437 in main src/pam_test.c:50
    #4 0x7f0d41f0c55f in __libc_start_call_main (/lib64/libc.so.6+0x2d55f)

SUMMARY: AddressSanitizer: 18 byte(s) leaked in 1 allocation(s).
```

## Tasks/Goals
- [ ] Find which commit introduced leak
- [ ] Patch to prevent leak

## Summary
*To fill out once the issue is to be closed. Give a short summary of the changes you made to implement or fix an issue*

**Comment by zakuArbor** [comment]
False alarm, binary was not rebuilt.
